### ISSUE TITLE
EXIF image rotation 問題

### ISSUE THREAD

**Issue by kevinphys** [FablabTaipei/FabDoc-alpha#15]
最簡單的解法是：

```
style="image-orientation: from-image;"
```

現在只支援 firefox, iOS Safari（4-5年前如此，到現在還是只有他們支援）
其他的瀏覽器都還在千里之外...

只能靠 server-side 處理，有沒有比較方便的處理方法？

目前有看到 exif.js 的讀取 tag 方法，不過要和 bootstrap 融合還要花一番心力。
不然大家現在都只能歪著頭看圖片啦。

**Comment by KinoLien** [comment]
Client的解法是用canvas API 去把圖片轉一下

Step 1. Read input file as DataURL, 查詢 [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL)

Step 2. 轉出來的DataURL 直接倒入image，如：  

```
var image = document.getElementById('myImage');
image.src = reader.results;
```

Step 3. New 一個 Canvas，用他的context物件倒入image  

```
var can = document.createElement('canvas');   
var w = image.width; 
var h = image.height;  
var ctx = can.getContext('2d');
can.width = w;
can.height = h;
ctx.drawImage(image, w, h);
```

然後[參考這](http://stackoverflow.com/questions/20600800/js-client-side-exif-orientation-rotate-and-mirror-jpeg-images)  
後續要接上傳的話可能還有3步⋯⋯囧
