### ISSUE TITLE
Safari 無法上傳，但 Chrome 可以

### ISSUE THREAD

**Issue by kevinphys** [FablabTaipei/FabDoc-alpha#16]
停在「Uploading photo...」，在「Almost there...」之前

先留著，睡醒再看
大家有空來解

**Comment by KinoLien** [comment]
剛剛解了一段
又出現一段
主因還是無法將轉出來的圖片轉成FileObject
Safari基於安全性的理由目前還不提供這種用法
所以我想說把原來的code變成是在view steps的時候才轉成正確方向

**Comment by kevinphys** [comment]
剛剛測了才發現 Safari 的登入 session 好像進不去，但 Chrome 運作滿正常的
