### ISSUE TITLE
如果要 render 頁面，一定要用到 Parse.View.extend 嗎？

### ISSUE THREAD

**Issue by kevinphys** [FablabTaipei/FabDoc-alpha#2]
1.6.12 是最新版的卻不支援 Parse.View
我不知道用一年多前舊版的 SDK (1.2.19)會不會出事，等等才要測試，但我想問的是：

一定要用到 Parse.Router.extend 才能做到 router 出新的路徑嗎？

**Comment by KinoLien** [comment]
我查了一下，有人[回答](http://stackoverflow.com/questions/33506588/parse-view-extend-cannot-read-property-extend-of-undefined)說目前的JS SDK 沒支援  

剛剛測試了一種方式
在目前gh-pages頁面裡

```
// 未登入前
var a = Parse.User.current();
// output: a = {_objCount: 0, className: "_User", id: "2Iz44XDLFC"}

// 登入後則會出現
// output: a = {_objCount: 1, className: "_User", id: "bkOLU3Rvr8"}
// 這時輸入
a.getUsername();
// output: "kino"
```

所以應該可以先用`Parse.User.current().getUsername()`去判斷使用者登入了沒
跳頁的話可以用Jquery的方式把HTML替換掉
這種方式目前最popular library是 ReactJS
可以用JQuery或ReactJS試試看
但這招就是以不跳頁的方式達到看起來像跳頁的功能

**Comment by kevinphys** [comment]
我發現問的有點錯，因為應該是原本有 Parse.Router.extend 可以支援跳頁。
不過也沒差，因為無論是 Parse.View 或 Parse.Router 現在都沒有支援....

我試試看 ReactJS
但發現硬是載入舊版的 SDK (parse-1.2.19)，好像還是可行？

**Comment by kevinphys** [comment]
哦哦，原來官方有啊，一種捨棄 Backbone的概念。
[Parse+React](https://github.com/ParsePlatform/ParseReact)
